"""
Critic Component for Markdown QA
Evaluates Markdown content against the Manifest, Project Brief, and Raw Materials.
Uses un-cut context and streaming for robustness.
"""

import json
from pathlib import Path
from typing import Dict, Optional, List
from src.core.gemini_client import GeminiClient
from src.core.json_utils import parse_json_dict_robust

CRITIC_SYSTEM_PROMPT = """You are a Ruthless Scientific Editor and Lead QA Engineer. 
Your goal is to perform a rigorous audit of the generated Markdown content against the provided Project Manifest and Project Brief.

### Evaluation Protocol:
1. **Manifest Alignment (CRITICAL)**: 
   - Open the Project Manifest. 
   - For EACH section, check if the actual content covers the "summary" and "knowledge_map" points.
   - If a specific mathematical derivation or concept is mentioned in the Manifest summary but is MISSING or too thin in the text, you MUST give a "MODIFY" or "REWRITE" verdict.
2. **Technical Rigor**:
   - Verify all MathJax equations. Are they present where requested?
   - Is the "Technical Vibe" from the Manifest being maintained?
3. **Logic & Narrative**:
   - Does each section transition naturally to the next?
   - Is the language consistent with the Project Brief?
4. **Formatting**:
   - Check for broken Mermaid/SVG blocks, duplicate titles, or improper heading levels.

### Verdicts:
- **APPROVE**: Perfect alignment for the sections currently being reviewed.
- **MODIFY**: Content is good but misses specific technical points, has typos, or formatting issues within the PRESENT sections.
- **REWRITE**: ONLY use if the present content is in the wrong language, is purely hallucinated, or is technically nonsensical. **DO NOT** use for missing future chapters.

### Output Format (JSON):
{
  "verdict": "APPROVE" | "MODIFY" | "REWRITE",
  "feedback": "Explain EXACTLY what is missing or incorrect in the PROVIDED text.",
  "section_feedback": {
      "filename.md": "Specific issue in this file.",
      "..."
  }
}

NOTE: You are auditing a WORK IN PROGRESS. If Section 1 is perfect, verdict must be "APPROVE" even if Section 2 and 3 are not yet provided. Do NOT be pedantic about the future.
"""

async def run_markdown_critic(
    client: GeminiClient,
    state, # AgentState
    merged_content: str,
    debug: bool = False
) -> Dict:
    """
    Run the Critic to evaluate content.
    """
    # 1. Prepare Manifest & Context (SOTA: Filter to only include PRESENT sections)
    present_section_ids = [Path(p).stem for p in state.completed_md_sections]
    
    manifest_info = {
        "project_title": state.manifest.project_title,
        "sections": [
            {
                "id": s.id, 
                "title": s.title, 
                "summary": s.summary,
                "metadata": s.metadata
            } for s in state.manifest.sections if s.id in present_section_ids
        ]
    }
    
    file_list = [Path(p).name for p in state.completed_md_sections]

    prompt = f"""# Manifest
{json.dumps(manifest_info, indent=2, ensure_ascii=False)}

# Project Brief
{state.project_brief}

# 🎯 User Intent
{state.user_intent}

# 📚 Reference Materials
{state.reference_materials}

# Available Files
{json.dumps(file_list, indent=2)}

# Merged Markdown Content
{merged_content}

---
Evaluate the content above. 
If the content is in the wrong language (e.g., English instead of Chinese), verdict MUST be "REWRITE".
If the content has factual errors or minor style issues, verdict "MODIFY".
If perfect, "APPROVE".
"""

    if debug:
        print(f"    [Critic] Prompt size: {len(prompt)} chars")

    # 2. Call API with Streaming enabled (Reverted to stream=True as requested)
    response = await client.generate_async(
        prompt=prompt,
        system_instruction=CRITIC_SYSTEM_PROMPT,
        temperature=0.0,
        stream=True
    )
    
    if not response.success:
        print(f"    [Critic] ❌ API Failed: {response.error}")
        return {"verdict": "REWRITE", "feedback": f"API Error, please retry. Details: {response.error}"}

    text = response.text.strip()
    
    # 3. Parse JSON using robust utility
    result = parse_json_dict_robust(text)
    if result and "verdict" in result:
        # Normalize verdict keys
        result["verdict"] = result["verdict"].upper()
        return result
    else:
        print(f"    [Critic] ❌ JSON Parse Error. Attempting salvage via Flash...")
        
        # SOTA: Emergency Salvage logic
        # We ask a lightweight model to just extract the JSON from the mess
        salvage_prompt = f"""The following text was generated by a scientific editor but the JSON is malformed. 
Extract and fix the JSON. Ensure the output is ONLY a valid JSON object with 'verdict', 'feedback', and 'section_feedback' keys.

Malformed Text:
{text[:4000]}
"""
        try:
            salvage_resp = await client.generate_async(
                prompt=salvage_prompt,
                system_instruction="You are a JSON recovery expert. Output ONLY valid JSON.",
                temperature=0.0
            )
            if salvage_resp.success:
                salvaged_result = parse_json_dict_robust(salvage_resp.text)
                if salvaged_result and "verdict" in salvaged_result:
                    print(f"    [Critic] ✅ Salvage SUCCESS.")
                    salvaged_result["verdict"] = salvaged_result["verdict"].upper()
                    return salvaged_result
        except Exception as e:
            print(f"    [Critic] ❌ Salvage failed: {e}")

        # If salvage fails, log to file for human audit
        log_file = Path(state.workspace_path) / "debug_failed_critic_json.txt"
        log_file.write_text(text, encoding="utf-8")
        print(f"    [Critic] 📝 Raw failed output saved to {log_file}")

        # SOTA Safety: Default to MODIFY
        return {
            "verdict": "MODIFY", 
            "feedback": f"Critical Error: AI output was not valid JSON even after salvage. Raw saved to workspace.",
            "section_feedback": {}
        }
